### ISSUE TITLE
Fix segfault with arrow example

### ISSUE THREAD

**Issue by kratsg** [kratsg/awkward-arrow-cmake-pybind11#6]
```
[root@dab7bb04d93f awkward-arrow-cmake-pybind11]# ./run_example.sh 
/Users/kratsg/awkward-arrow-cmake-pybind11/examples /Users/kratsg/awkward-arrow-cmake-pybind11
* Reading CSV file 'test.csv' into table
./run_example.sh: line 18:   351 Segmentation fault      ./../build/example_arrow
```

and it seems like gdb indicates probably a double-delete maybe?

```
[root@dab7bb04d93f examples]# gdb ./../build/example_arrow 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /Users/kratsg/awkward-arrow-cmake-pybind11/build/example_arrow...(no debugging symbols found)...done.
(gdb) run
Starting program: /Users/kratsg/awkward-arrow-cmake-pybind11/examples/./../build/example_arrow 
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7f87577ff700 (LWP 428)]
* Reading CSV file 'test.csv' into table

Program received signal SIGSEGV, Segmentation fault.
0x00007f8758fd6de4 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() () from /lib64/libstdc++.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-324.el7_9.x86_64 libgcc-4.8.5-44.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64
(gdb) bt
#0  0x00007f8758fd6de4 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() () from /lib64/libstdc++.so.6
#1  0x000000000040430f in void std::_Destroy<std::string>(std::string*) ()
#2  0x00000000004041ee in void std::_Destroy_aux<false>::__destroy<std::string*>(std::string*, std::string*) ()
#3  0x0000000000404043 in void std::_Destroy<std::string*>(std::string*, std::string*) ()
#4  0x0000000000403893 in void std::_Destroy<std::string*, std::string>(std::string*, std::string*, std::allocator<std::string>&) ()
#5  0x0000000000403187 in std::vector<std::string, std::allocator<std::string> >::~vector() ()
#6  0x0000000000402f3a in arrow::csv::ConvertOptions::~ConvertOptions() ()
#7  0x0000000000401e50 in (anonymous namespace)::RunMain(int, char**) ()
#8  0x0000000000402697 in main ()
```

**Comment by kratsg** [comment]
With debugging information added

```
[root@dab7bb04d93f examples]# gdb ./../build/example_arrow 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /Users/kratsg/awkward-arrow-cmake-pybind11/build/example_arrow...done.
(gdb) run
Starting program: /Users/kratsg/awkward-arrow-cmake-pybind11/examples/./../build/example_arrow 
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7f9c58dff700 (LWP 1643)]
* Reading CSV file 'test.csv' into table

Program received signal SIGSEGV, Segmentation fault.
__destroy<std::basic_string<char>*> (__last=<optimized out>, __first=0x3200000000) at /usr/include/c++/4.8.2/bits/stl_construct.h:103
103		    std::_Destroy(std::__addressof(*__first));
Missing separate debuginfos, use: debuginfo-install glibc-2.17-324.el7_9.x86_64 libgcc-4.8.5-44.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64
(gdb) bt
#0  __destroy<std::basic_string<char>*> (__last=<optimized out>, __first=0x3200000000) at /usr/include/c++/4.8.2/bits/stl_construct.h:103
#1  _Destroy<std::basic_string<char>*> (__last=<optimized out>, __first=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_construct.h:126
#2  _Destroy<std::basic_string<char>*, std::basic_string<char> > (__last=0x0, __first=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_construct.h:151
#3  ~vector (this=0x7ffff43602a8, __in_chrg=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_vector.h:415
#4  arrow::csv::ConvertOptions::~ConvertOptions (this=0x7ffff4360220, __in_chrg=<optimized out>)
    at /usr/local/venv/lib/python3.8/site-packages/pyarrow/include/arrow/csv/options.h:64
#5  0x000000000040171a in (anonymous namespace)::RunMain (argv=<optimized out>, argc=<optimized out>, this=<optimized out>, this=<optimized out>)
    at /Users/kratsg/awkward-arrow-cmake-pybind11/src/example/arrow.cpp:39
#6  0x000000000040135f in main (argc=<optimized out>, argv=<optimized out>) at /Users/kratsg/awkward-arrow-cmake-pybind11/src/example/arrow.cpp:66
```

**Comment by kratsg** [comment]
For now, filed an issue here https://issues.apache.org/jira/browse/ARROW-13085

**Comment by kratsg** [comment]
Resolved by fixing toolchain. See apache/arrow#10535
